# Rogaine Analysis

## Libraries

```{r}
library(tidyverse)
library(viridis)
```

## Importing the Data

```{r}
DayRogaine <- read_csv('raw_data/DayRogaineResults.csv')
NightRogaine <- read_csv('raw_data/NightRogaineResults.csv')
```

## Day Rogaine

Histogram

```{r}
ggplot(DayRogaine, aes(Score, fill = Lodge)) +
  geom_histogram( binwidth = 10) +
  labs(x = "Score", y = "Count", title = "Dristribution of Scores - Day Rogaine")
```

Bar Chart

```{r}
ggplot(DayRogaine, aes(x= Pl, y=Score, fill=Lodge)) +
  geom_bar(stat = "identity") +
  labs(x = "Team Position", y = "Score", title = "Team Scores by Overall Position - Day Rogaine") +
  geom_hline(yintercept = 750) +
  annotate("text", x = 50, y = 800, label = "Revised Div 1-3 Qualify") +
  geom_hline(yintercept = 450) +
  annotate("text", x = 50, y = 500, label = "Revised Div 4-7 Qualify") +
  geom_hline(yintercept = 1050, linetype = 2) +
  annotate("text", x = 50, y = 1100, label = "Original Div 1-3 Qualify") +
  geom_hline(yintercept = 850, linetype = 2) +
  annotate("text", x = 50, y = 900, label = "Original Div 4-7 Qualify")

# stat = "identity" argument tells ggplot2 to use the values in the "Score" column directly as the heights of the bars

```

## Night Rogaine

Histogram

```{r}
ggplot(NightRogaine, aes(Score, fill = Lodge)) +
  geom_histogram( binwidth = 10) +
  labs(x = "Score", y = "Count", title = "Dristribution of Scores - Night Rogaine")
```

Bar Chart

```{r}
ggplot(NightRogaine, aes(x= Pl, y=Score, fill=Lodge)) +
  geom_bar(stat = "identity") +
  labs(x = "Team Position", y = "Score", title = "Team Scores by Overall Position - Night Rogaine") +
  geom_hline(yintercept = 600) +
  annotate("text", x = 50, y = 580, label = "Revised Div 1-3 Qualify") +
  geom_hline(yintercept = 350) +
  annotate("text", x = 50, y = 400, label = "Revised Div 4-7 Qualify") +
  geom_hline(yintercept = 900, linetype = 2) +
  annotate("text", x = 50, y = 950, label = "Original Div 1-3 Qualify") +
  geom_hline(yintercept = 650, linetype = 2) +
  annotate("text", x = 50, y = 700, label = "Original Div 4-7 Qualify")

# stat = "identity" argument tells ggplot2 to use the values in the "Score" column directly as the heights of the bars

```
